version: "3"
services:
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    network_mode: "host"
    volumes:
      - /home/mysql/config:/config
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    network_mode: "host"
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
